data:
  root: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data"
  train: valid
  val: valid
  names: ['Ambulance', 'Bus', 'Car', 'Motorcycle', 'Truck']

model:
  backbone: resnet18
  pretrained: true
  backbone_output_channels: 512
  detector_hidden_sz: 1024
  input_size: [224, 224]
  S: 7
  B: 1
  nc: 5
  conf_th: 0.0

training:
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  epochs: 50
  checkpoints_dir: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints"

inference:
  batch_size: 2
  source: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data/valid/images"
  checkpoint: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints/final_epoch_50.pt"
