data:
  root: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data"
  train: valid
  val: valid
  names: ['Ambulance', 'Bus', 'Car', 'Motorcycle', 'Truck']
  augmentations:
    horizontal_flip: 0.8
    vertical_flip: 0.0
    brightness_contrast: 0.8
    random_crop: 0.8
    random_crop_dims: [224, 224]

model:
  backbone: resnet34
  pretrained: true
  freeze_backbone: true
  backbone_output_channels: 512
  detector_hidden_sizes: [1024, 512]
  input_size: [224, 224]
  S: 7
  B: 1
  nc: 5

training:
  epochs: 100
  checkpoints_dir: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints"
  save_freq: 20
  dls_kwargs:
    pin_memory: true
    batch_size: 32
    drop_last: true
    num_workers: 2
  optim_kwargs:
    lr: 0.001
    weight_decay: 0.0001
  loss:
    l_coord: 5.0
    l_obj: 1.5
    l_noobj: 0.5
    l_class: 1.0

inference:
  conf_th: 0.4
  dls_kwargs:
    pin_memory: false
    batch_size: 4
    drop_last: false
    num_workers: 2
  source: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data/valid/images"
  checkpoint: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints/final_epoch_50.pt"
