data:
  root: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data"
  train: valid
  val: valid
  names: ['Ambulance', 'Bus', 'Car', 'Motorcycle', 'Truck']
  augmentations:
    horizontal_flip: 0.8
    vertical_flip: 0.0
    brightness_contrast: 0.8
    random_crop: 0.8
    random_crop_dims: [224, 224]

model:
  backbone: resnet18
  pretrained: true
  freeze_backbone: true
  backbone_output_channels: 512
  detector_hidden_sizes: [1024, 512]
  input_size: [224, 224]
  S: 7
  B: 1
  nc: 5
  conf_th: 0.0

training:
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  epochs: 30
  checkpoints_dir: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints"
  save_freq: 10

inference:
  batch_size: 2
  source: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data/valid/images"
  checkpoint: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints/final_epoch_50.pt"
