data:
  root: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data"
  train: train
  val: valid
  names: ['Ambulance', 'Bus', 'Car', 'Motorcycle', 'Truck']
  class_weights: [0.40, 0.24, 0.12, 0.36, 0.32]
  augmentations:
    apply: true
    horizontal_flip: 0.5
    color_jitter: 1.0
    shift_scale_rotate: 0.9
    random_crop: 0.9
    random_crop_dims: [448, 448]
    gaussian_noise: 0.2

model:
  backbone: resnet18
  pretrained: true
  freeze_backbone: true
  conv_block_channels: [256]
  detector_hidden_sz: 256
  input_size: [448, 448]
  S: 7
  B: 2
  nc: 5

training:
  epochs: 40
  checkpoints_dir: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints"
  save_freq: 20
  val_freq: 1
  dls_kwargs:
    pin_memory: true
    batch_size: 32
    drop_last: true
    num_workers: 2
  optim_kwargs: {}
    # weight_decay: 0.0005
    # momentum: 0.9
  loss:
    l_coord: 7.0
    l_obj: 2.0
    l_noobj: 2.0
    l_class: 1.5

inference:
  prob_th: 0.1
  dls_kwargs:
    pin_memory: false
    batch_size: 4
    drop_last: false
    num_workers: 2
  source: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data/valid/images"
  checkpoint: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/checkpoints/final_epoch_200.pt"

lr: 0.0003
