data:
  root: "/home/ajkdrag/workspace/projects/architectures-impl-pytorch/.data"
  train: train
  val: valid
  names: ['Ambulance', 'Bus', 'Car', 'Motorcycle', 'Truck']

training:
  batch_size: 8
  num_workers: 4
  learning_rate: 0.001
  epochs: 50

model:
  backbone: resnet18
  pretrained: true
  backbone_output_channels: 512
  detector_hidden_sz: 1024
  input_size: [224, 224]
  S: 7
  B: 1
  nc: 5
